/*
  *
  *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
  *
  *   This file is a wrapper S-function produced by the S-Function
  *   Builder which only recognizes certain fields.  Changes made
  *   outside these fields will be lost the next time the block is
  *   used to load, edit, and resave this file. This file will be overwritten
  *   by the S-function Builder block. If you want to edit this file by hand, 
  *   you must change it only in the area defined as:  
  *
  *        %%%-SFUNWIZ_wrapper_XXXXX_Changes_BEGIN 
  *            Your Changes go here
  *        %%%-SFUNWIZ_wrapper_XXXXXX_Changes_END
  *
  *   For better compatibility with the Simulink Coder, the
  *   "wrapper" S-function technique is used.  This is discussed
  *   in the Simulink Coder User's Manual in the Chapter titled,
  *   "Wrapper S-functions".
  *
  *   Created: Mon Apr 23 15:50:51 2018
  */


/*
 * Include Files
 *
 */
#if defined(MATLAB_MEX_FILE)
#include "tmwtypes.h"
#include "simstruc_types.h"
#else
#include "rtwtypes.h"
#endif

//!!!!!!!!!!!!!!!!!!!!!!!!!!!
//本文件被用来控制模块了，与文件名称不一致

/* %%%-SFUNWIZ_wrapper_includes_Changes_BEGIN --- EDIT HERE TO _END */
#include <math.h>
#include <stdlib.h>
#include <stdio.h>
#include "TU5011.h"

static char  g_szMsg[128];
static void ErrorPrint(char *str)
{
	static FILE *fp = 0;
	if( fp == 0)
	{
		fp = fopen("/tmp/KL_Uart_ctllog.txt","w");
	}
	
	if( fp != 0)
	{
		fprintf(fp, "%s\n",str);
		fflush(fp);
	}
}

#define PS3510SERIAL_MAXDEV 256
PS_DevHandle g_ps3510_handle[PS3510SERIAL_MAXDEV][PS3510SERIAL_MAXDEV] = {0};
int g_ps3510_DevInited[PS3510SERIAL_MAXDEV][PS3510SERIAL_MAXDEV] = {0};

void kl_serial_send_sfun_Start_wrapper(const real_T *u0,
                          const real_T *u1,
                          const real_T *u2,
                          real_T *y0,
                          real_T *y1,
                          real_T *y2  , 
                          const real_T  *ctlid, const int_T  p_width0, 
                          const real_T  *baud, const int_T  p_width1, 
                          const real_T  *lenbit, const int_T  p_width2, 
                          const real_T  *paritybit, const int_T  p_width3, 
                          const real_T  *stopbit, const int_T  p_width4, 
                          const real_T  *parityenbale, const int_T  p_width5, 
                          const real_T  *mode, const int_T  p_width6, 
                          const real_T  *choosewrongdata, const int_T  p_width7, 
                          const real_T  *sendchl, const int_T  p_width8, 
                          const real_T  *resv0, const int_T  p_width9, 
                          const real_T  *resv1, const int_T  p_width10, 
                          const real_T  *resv2, const int_T  p_width11, 
                          const real_T  *resv3,  const int_T p_width12,
			     const int_T y_width, const int_T u_width)
{
	int id = (int)*ctlid -1;
	int pxim = (int)*resv0;
	int pxin = (int)*resv1;
	int Channel = (int)*sendchl - 1;
	int txrx = (int)*resv2;
	char buf[64] = {0};
	AsyncChannelMode 	ModeAsy;
	int result = PS_SUCCESS;
	int pri = (int)*paritybit;
	int stop = (int)*stopbit;
	int mode1 = (int)*mode;
	int res = (int)*resv3;
	int devtype = (int)*choosewrongdata;
	int _baud = (int)*baud;
	int actual_baud = 9600;

	
	if (devtype == 1) {//TU-5011
		if (g_ps3510_DevInited[pxim][pxin] == 0) {
			sprintf(buf,"PXI%d::%d::INSTR",pxim,pxin);
			
			result = TU5011_OpenDeviceByName(buf, &g_ps3510_handle[pxim][pxin]); /// 根据资源名称打开板卡
			if(result != 0)
			{
				// printf("Open device is error，The error code is %d.\n", result);
				sprintf(g_szMsg," error，The error code is %d.\n", result);
				ErrorPrint(g_szMsg);
				
				return ;
			}
			else
			{
				g_ps3510_DevInited[pxim][pxin] = 1;
				
				sprintf(g_szMsg,"ps3510 ctl in ...Open PXI%d::%d ,chl:%d,baud:%d,pri:%d",pxim,pxin,Channel,(int)*baud,pri);
				ErrorPrint(g_szMsg);
				// printf("Open device Success!\n");
				sprintf(g_szMsg," Success!");
				ErrorPrint(g_szMsg);
			}
		}
			
		if (g_ps3510_DevInited[pxim][pxin] == 1) {
			TU5011_ClearSendFIFO(g_ps3510_handle[pxim][pxin], Channel);
			
			if (_baud == 1) {
				actual_baud = 50;
			}
			if (_baud == 2) {
				actual_baud = 75;
			}
			if (_baud == 3) {
				actual_baud = 110;
			}
			if (_baud == 4) {
				actual_baud = 134;
			}
			if (_baud == 5) {
				actual_baud = 150;
			}
			if (_baud == 6) {
				actual_baud = 200;
			}
			if (_baud == 7) {
				actual_baud = 300;
			}
			if (_baud == 8) {
				actual_baud = 600;
			}
			if (_baud == 9) {
				actual_baud = 1200;
			}
			if (_baud == 10) {
				actual_baud = 1800;
			}
			if (_baud == 11) {
				actual_baud = 2400;
			}
			if (_baud == 12) {
				actual_baud = 4800;
			}
			if (_baud == 13) {
				actual_baud = 9600;
			}
			if (_baud == 14) {
				actual_baud = 38400;
			}
			if (_baud == 15) {
				actual_baud = 57600;
			}
			if (_baud == 16) {
				actual_baud = 76800;
			}
			if (_baud == 17) {
				actual_baud = 115200;
			}
			if (_baud == 18) {
				actual_baud = (int)*resv3;
			}
			ModeAsy.baudrate = actual_baud;
			ModeAsy.lengthBit = (int)*lenbit - 1;
			
			// if (pri == 1)
				// ModeAsy.parityBit = Bit0;
			// if (pri == 2)
				// ModeAsy.parityBit = Bit1;
			if (pri == 1)
				ModeAsy.parityBit = Odd;
			if (pri == 2)
				ModeAsy.parityBit = Even;
			
			if (stop == 1)
				ModeAsy.stopBit = stop1;
			// if (stop == 2)
				// ModeAsy.stopBit = stop1_5;
			if (stop == 2)
				ModeAsy.stopBit = stop2;
			
			ModeAsy.ParityEnable = 1;
			
			if (mode1 == 1)
				ModeAsy.serialMode = RS422;
			if (mode1 == 2)
				ModeAsy.serialMode = RS485;
			if (mode1 == 3)
				ModeAsy.serialMode = RS232;
			
			ModeAsy.TermiResistor = 0;
			ModeAsy.ChooseWrongData = 0;
			
			
			sprintf(g_szMsg,"%d %d %d %d %d %d %d %d.\n", ModeAsy.baudrate,ModeAsy.lengthBit,ModeAsy.parityBit,\
											ModeAsy.stopBit,ModeAsy.ParityEnable,ModeAsy.serialMode,ModeAsy.TermiResistor,ModeAsy.ChooseWrongData);
			ErrorPrint(g_szMsg);
			
			// ModeAsy.baudrate = 9600;
			// ModeAsy.lengthBit = Data8;
			// ModeAsy.parityBit = Odd;
			// ModeAsy.stopBit = stop1;
			// ModeAsy.ParityEnable = 1;
			// ModeAsy.serialMode = RS232;
			// ModeAsy.TermiResistor = 0;
			// ModeAsy.ChooseWrongData = 0;			
			
			TU5011_SetAsyncChannelMode(g_ps3510_handle[pxim][pxin], Channel, ModeAsy);
			
			if (txrx == 1) {
				TU5011_EnableSend(g_ps3510_handle[pxim][pxin], Channel, 1);
			}
			if (txrx == 2) {
				TU5011_EnableReceive(g_ps3510_handle[pxim][pxin], Channel, 1);
			}
		}
	}	
}

void kl_serial_send_sfun_Outputs_wrapper(const real_T *u0,
                          const real_T *u1,
                          const real_T *u2,
                          real_T *y0,
                          real_T *y1,
                          real_T *y2  , 
                          const real_T  *ctlid, const int_T  p_width0, 
                          const real_T  *baud, const int_T  p_width1, 
                          const real_T  *lenbit, const int_T  p_width2, 
                          const real_T  *paritybit, const int_T  p_width3, 
                          const real_T  *stopbit, const int_T  p_width4, 
                          const real_T  *parityenbale, const int_T  p_width5, 
                          const real_T  *mode, const int_T  p_width6, 
                          const real_T  *choosewrongdata, const int_T  p_width7, 
                          const real_T  *sendchl, const int_T  p_width8, 
                          const real_T  *resv0, const int_T  p_width9, 
                          const real_T  *resv1, const int_T  p_width10, 
                          const real_T  *resv2, const int_T  p_width11, 
                          const real_T  *resv3,  const int_T p_width12,
			     const int_T y_width, const int_T u_width)
{

}

void kl_serial_send_sfun_Terminate_wrapper(const real_T *u0,
                          const real_T *u1,
                          const real_T *u2,
                          real_T *y0,
                          real_T *y1,
                          real_T *y2  , 
                          const real_T  *ctlid, const int_T  p_width0, 
                          const real_T  *baud, const int_T  p_width1, 
                          const real_T  *lenbit, const int_T  p_width2, 
                          const real_T  *paritybit, const int_T  p_width3, 
                          const real_T  *stopbit, const int_T  p_width4, 
                          const real_T  *parityenbale, const int_T  p_width5, 
                          const real_T  *mode, const int_T  p_width6, 
                          const real_T  *choosewrongdata, const int_T  p_width7, 
                          const real_T  *sendchl, const int_T  p_width8, 
                          const real_T  *resv0, const int_T  p_width9, 
                          const real_T  *resv1, const int_T  p_width10, 
                          const real_T  *resv2, const int_T  p_width11, 
                          const real_T  *resv3,  const int_T p_width12,
			     const int_T y_width, const int_T u_width)
{
	int id = (int)*ctlid;
	int result = PS_SUCCESS;
	int pxim = (int)*resv0;
	int pxin = (int)*resv1;
	
	if (g_ps3510_DevInited[pxim][pxin] == 1) {
		g_ps3510_DevInited[pxim][pxin] = 0;
		result = TU5011_CloseDevice(g_ps3510_handle[pxim][pxin]);
		if(result != 0)
		{
			// printf("Close device is error，The error code is %d.\n", result);
			return ;
		}	
	}
}








